language: node_js
node_js:
  - "6.9.1"
branches:
  only:
    - master



berfore_script:
  - npm i

script:
  - npm run lib
  - npm run build && sh ./scripts/git-page.sh

deploy:
  skip_cleanup: true
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_TOKEN}
  on:
    tags: true
